# Generated by Django 5.0.3 on 2024-07-13 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeptModel',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dept', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cmsapp.deptmodel')),
            ],
        ),
    ]
